# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='shows',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.Network'),
        ),
    ]
